[workspace]
channels = [
  "conda-forge",
  "bioconda",
  "kuleuven-micas",
  "KEKE046",
  "JosseVanDelm",
]
name = "schnitzel"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.34" }

[tasks]

[dependencies]
elfio = ">=3.12,<4"
cpp-argparse = ">=3.2,<4"
python = ">=3.12,<3.13"
just = ">=1.46.0,<2"
lit = ">=22.1.0,<23"
pre-commit = ">=4.5.1,<5"
pytest = "<9"


[pypi-dependencies]
schnitzel = { path = ".", editable = true }
xdsl = { git = "https://github.com/xdslproject/xdsl.git", rev = "af4e063ee948b8f62fd8476d2f25d0b018bc274c" }
minimalloc = { git = "https://github.com/jorendumoulin/minimalloc.git", rev = "917a2ddf8ea0f48c7c77145d57c21d7c5dd20ef2" }
filecheck = ">=1.0.3, <2"
pyyaml = ">=6.0.3, <7"

# Compiler dependencies, these should preferably be installed locally
# but are available here for quick starts and ci
[feature.compiler.dependencies]
cmake = ">=4.2.3,<5"
ccache = ">=4.12.2,<5"
clang = ">=21.1.8,<22"
ninja = ">=1.13.2,<2"
lld = ">=21.1.8,<22"
verilator = "==5.044"
openjdk = ">=21,<22"

# Conda-packaged riscv-gnu-toolchain:
[feature.riscv-gnu-toolchain.dependencies]
riscv-gnu-toolchain = "==2026.01.23nightly"

[feature.torch.pypi-dependencies]
executorch = ">=1.1.0, <2"
torch = { version = "==2.10.0", index = "https://download.pytorch.org/whl/cpu" }
torchgen = ">=0.0.1, <0.0.2"

# TODO: merge old snax-mlir dependencies
# [project.optional-dependencies]
#
# # All optional dependencies for plotting and parsing
# dev = ["pre-commit", "filecheck==1.0.3", "lit", "pytest"]
#
# # All optional dependencies for graphical plotting
# viz = ["pandas", "matplotlib"]
#
# # Dependencies for neural network compilation
# nn = ["tensorflow-cpu==2.19.0"]


# [feature.phs.dependencies]
# circt = { version = "==1.122.0", channel = "KEKE046" }
# openjdk = "==17.0.17"
# mill = "==0.11.8"

# [tool.pixi.dependencies]
# mlir = "==21.1.1"
# clang = "==21.1.1"
# lld = "==21.1.1"
# snax-cluster-prebuilt = "==0.2.19"
# snakemake-minimal = "*"
# pyright = ">=1.1.407,<2"
# vcd-to-csv = { version = ">=0.1.0,<0.2", channel = "kuleuven-micas" }

# Dependencies only needed for executorch development:
[environments]
default = ["torch", "riscv-gnu-toolchain"]
torch = ["torch", "riscv-gnu-toolchain"]
rtl = ["compiler", "riscv-gnu-toolchain"]
all = ["compiler", "torch", "riscv-gnu-toolchain"]
minimal = []
