package sim

import chisel3._
import circt.stage.ChiselStage
import top.{Top, TensorTop}
import config.SystemConfig
import upickle.default.write
import java.io.File
import java.io.PrintWriter

/** Elaboration object to generate Verilog for spitchel integration
  *
  * This generates the Verilog RTL that will be verilated and integrated with the spike/fesvr infrastructure.
  *
  * Pass `--top=<name>` to select which top-level module to elaborate. Extend the match below to add new
  * configurations.
  */
object EmitVerilog extends App {

  val topName: String = args
    .collectFirst { case s if s.startsWith("--top=") => s.stripPrefix("--top=") }
    .getOrElse("tensor")

  val outputDir: String = args
    .collectFirst { case s if s.startsWith("--output-dir=") => s.stripPrefix("--output-dir=") }
    .getOrElse("generated")

  println(s"Generating Verilog for Schnitzel Core (top=$topName, output=$outputDir)...")

  var topConfig: SystemConfig = null

  ChiselStage.emitSystemVerilogFile(
    topName match {
      case "tensor"  => val m = new TensorTop; topConfig = m.getConfig; m
      case "default" => val m = new Top; topConfig = m.getConfig; m
      case other     => sys.error(s"Unknown --top value '$other'.")
    },
    args = Array("--target-dir", outputDir),
    firtoolOpts = Array(
      "-disable-all-randomization",
      "-strip-debug-info",
      "--enable-layers=Verification,Verification.Assert,Verification.Assume,Verification.Cover"
    )
  )

  val pw = new PrintWriter(new File(s"$outputDir/config.json"))
  try {
    pw.write(write(topConfig, indent = 2))
    println(s"Successfully generated metadata at $outputDir/config.json")
  } finally {
    pw.close()
  }

  // Emit a Bender.yml fragment for this generated directory. The root
  // schnitzel Bender.yml depends on this as a path-dep so that downstream
  // tooling (`bender script verilator|genus|...`) sees the chisel sources
  // along with the rest of the design. Order matches `filelist.f` for any
  // files in it (firtool's intended elaboration order); any addPath-emitted
  // resources (e.g. cva6_wrapper_flattened.sv) appear afterwards.
  val filelistFile = new File(s"$outputDir/filelist.f")
  val filelistOrder: Seq[String] =
    if (filelistFile.exists) {
      val src = scala.io.Source.fromFile(filelistFile)
      try src.getLines().map(_.trim).filter(_.nonEmpty).toList
      finally src.close()
    } else Nil

  val allSvFiles: Seq[String] = Option(new File(outputDir).listFiles())
    .map(_.toSeq)
    .getOrElse(Seq.empty)
    .map(_.getName)
    .filter(_.endsWith(".sv"))
    .sorted

  val orderedFiles: Seq[String] =
    filelistOrder ++ allSvFiles.filterNot(filelistOrder.contains)

  val benderPw = new PrintWriter(new File(s"$outputDir/Bender.yml"))
  try {
    benderPw.write("# Auto-generated by sim.EmitVerilog — do not edit by hand.\n")
    benderPw.write("package:\n")
    benderPw.write("  name: schnitzel_rtl\n")
    benderPw.write("  authors: [\"auto-generated\"]\n\n")
    benderPw.write("sources:\n")
    orderedFiles.foreach(f => benderPw.write(s"  - $f\n"))
    println(s"Successfully generated $outputDir/Bender.yml (${orderedFiles.size} files)")
  } finally {
    benderPw.close()
  }

  println(s"Verilog generated in $outputDir/")
}
