name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          activate-environment: true
      - name: build all
        run: just build
