name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          activate-environment: true
      - name: Checkout Selective Submodules
        run: git submodule update --init --recursive --depth 1 \
          "submodules/cva6" \
          "submodules/ibex" \
          "submodules/printf"
      - name: Generate Verilog
        run: just generate-verilog
      - name: Configure All Build Systems
        run: just configure
      - name: Build Everything
        run: just build
