name: lit-tests (easyfloat)
on:
  push:
    branches: ["main"]
    paths:
      - 'tests/filecheck/transforms/hardfloat/convert-hardfloat-to-hw*.mlir'
  pull_request:
    paths:
      - 'tests/filecheck/transforms/hardfloat/convert-hardfloat-to-hw*.mlir'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  python-tests:
    if: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          path: snax-mlir
      - name: Checkout kuleuven-easyfloat
        uses: actions/checkout@v4
        with:
          ref: 14a0ace151927575f12188d7139585c5420d2dee
          repository: KULeuven-MICAS/kuleuven-easyfloat
          path: kuleuven-easyfloat
      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          manifest-path: snax-mlir/pyproject.toml
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Test with lit
        shell: bash
        working-directory: snax-mlir
        run: |
          pixi run lit -v tests/filecheck/transforms/hardfloat/ -Dforce-easyfloat=1
