name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  pyright:
    name: Pyright
    build:
      runs-on: ubuntu-latest
      env:
        PYRIGHT_VERSION: 1.0
      steps:
        - uses: actions/checkout@v5
        - uses: prefix-dev/setup-pixi@v0.9.4
          with:
            activate-environment: true
            environments: rtl
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        - name: check pyright
          run: pixi run pyright
  precommit:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Run code formatting checks with pre-commit
        uses: pre-commit/action@v3.0.1
