name: PHS - Build and run kernels
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-run-kernels:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        kernel: [streamer_phs_alu, streamer_phs_aluf, streamer_phs_accumulation]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: schnitzel
      - name: Checkout Selective Submodules
        run: git submodule update --init --recursive --depth 1 submodules/cva6 submodules/ibex submodules/printf
        working-directory: schnitzel
      - name: Checkout kuleuven-easyfloat
        uses: actions/checkout@v4
        with:
          repository: KULeuven-MICAS/kuleuven-easyfloat
          path: kuleuven-easyfloat
          ref: b755dcdce7a9df261feff2c654d62241034e6e4a
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          manifest-path: schnitzel/pixi.toml
          environments: phs
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Generate flattened BlackBox wrappers
        working-directory: schnitzel
        run: |
          pixi run -e phs make -C src/main/resources/ibex
          pixi run -e phs make -C src/main/resources/cva6
      - name: Build and run kernels
        run: pixi run -e phs snakemake -k -p -j $(nproc) all
        working-directory: schnitzel/kernels/${{ matrix.kernel }}
